name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  # job ou uma action
  minha-primeira-action:
    # em qual sistema operacional vai rodar
    runs-on: ubuntu-latest
    # aqui são os steps da job
    steps:
      - run: echo "Olá, essa é minha primeira action"