name: Meu Primeiro Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  # job ou uma action
  minha-primeira-action:
    # em qual sistema operacional vai rodar
    runs-on: ubuntu-latest
    # aqui são os steps da job
    steps:
      - run: echo "Configurado com pull request main"